version: '3.2'

services:
  app:
    build:
      dockerfile: build/docker/go/Dockerfile
      context: .
    container_name: pismo_app
    entrypoint: pismo
    ports:
      - '8080:8080'
    environment:
      - ENVIROMENT=local
    networks:
      - pismo
    depends_on:
      - db
  
  db:
    build: build/docker/mariadb
    platform: linux/amd64
    container_name: pismo_db
    ports:
      - '3306:3306'
    volumes:
      - /build/docker/mariadb/dbdata:/var/lib/mysql
      - /build/docker/mariadb/scripts:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - pismo

networks:
  pismo:
    driver: bridge